use std::collections::BTreeSet;

use unica_format_core::semantic_ids::{
    SemanticEnumValue, SemanticFacetId, SemanticObjectKind, SemanticPropertyId, SemanticRelationId,
};

fn assert_complete_unique<T: Copy>(
    actual: &[T],
    expected: &[&str],
    stable_string: impl Fn(T) -> &'static str,
) {
    let actual = actual
        .iter()
        .copied()
        .map(stable_string)
        .collect::<Vec<_>>();
    assert_eq!(actual, expected);
    assert_eq!(
        actual.iter().copied().collect::<BTreeSet<_>>().len(),
        actual.len(),
        "semantic registry contains duplicate stable strings"
    );
}

#[test]
fn property_registry_covers_the_approved_legacy_parity_vocabulary() {
    assert_complete_unique(
        SemanticPropertyId::ALL,
        &[
            "metadata.kind",
            "metadata.name",
            "metadata.uuid",
            "metadata.synonym",
            "metadata.comment",
            "metadata.code",
            "metadata.description",
            "presentation.object",
            "presentation.extendedObject",
            "presentation.list",
            "presentation.extendedList",
            "support.state",
            "support.authorability",
            "support.editCapability",
            "document.number.type",
            "document.number.length",
            "document.number.periodicity",
            "document.number.auto",
            "document.posting.mode",
            "document.realTimePosting.mode",
            "document.registerRecordsDeletion.mode",
            "document.registerRecordsWritingOnPost.mode",
            "catalog.hierarchy.type",
            "catalog.hierarchy.levelLimit",
            "catalog.code.length",
            "catalog.description.length",
            "register.periodicity",
            "register.writeMode",
            "register.type",
            "constant.value.type",
            "report.mainDataCompositionSchema",
            "definedType.type",
            "module.global",
            "module.clientManagedApplication",
            "module.server",
            "module.externalConnection",
            "module.clientOrdinaryApplication",
            "module.serverCall",
            "module.privileged",
            "module.returnValuesReuse",
            "job.method",
            "job.use",
            "job.predefined",
            "job.restart.count",
            "job.restart.interval",
            "job.key",
            "subscription.event",
            "subscription.handler",
            "subscription.source.type",
            "httpService.rootUrl",
            "httpService.reuseSessions",
            "httpService.sessionMaxAge",
            "httpService.urlTemplate.template",
            "httpService.method.httpMethod",
            "httpService.method.handler",
            "webService.namespace",
            "webService.xdtoPackages",
            "webService.descriptorFileName",
            "webService.reuseSessions",
            "webService.sessionMaxAge",
            "webService.operation.returnType",
            "webService.operation.nillable",
            "webService.operation.transactioned",
            "webService.operation.procedureName",
            "webService.parameter.type",
            "webService.parameter.nillable",
            "webService.parameter.direction",
            "field.type",
            "field.required",
            "field.fillChecking",
            "field.indexing",
            "field.multiLine",
            "field.use",
            "field.fillValue",
            "field.master",
            "field.mainFilter",
            "field.denyIncompleteValues",
            "field.length",
            "field.digits",
            "field.fractionDigits",
            "tabularSection.order",
            "tabularSection.lineNumberLength",
            "form.type",
            "template.type",
            "command.group",
            "command.representation",
            "command.useStandard",
            "help.includeInContents",
        ],
        SemanticPropertyId::as_str,
    );
}

#[test]
fn relation_facet_object_kind_and_enum_registries_are_complete_and_unique() {
    assert_complete_unique(
        SemanticRelationId::ALL,
        &[
            "children",
            "attributes",
            "dimensions",
            "resources",
            "tabularSections",
            "columns",
            "forms",
            "commands",
            "templates",
            "enumValues",
            "basedOn",
            "registerRecords",
            "urlTemplates",
            "methods",
            "operations",
            "parameters",
            "references",
        ],
        SemanticRelationId::as_str,
    );
    assert_complete_unique(
        SemanticFacetId::ALL,
        &[
            "identity",
            "presentation",
            "support",
            "numbering",
            "posting",
            "hierarchy",
            "typing",
            "fields",
            "moduleExecution",
            "scheduling",
            "subscription",
            "service",
            "operation",
            "structure",
        ],
        SemanticFacetId::as_str,
    );
    assert_complete_unique(
        SemanticObjectKind::ALL,
        &[
            "sourceRoot",
            "configuration",
            "document",
            "catalog",
            "informationRegister",
            "accumulationRegister",
            "accountingRegister",
            "calculationRegister",
            "constant",
            "report",
            "definedType",
            "commonModule",
            "scheduledJob",
            "eventSubscription",
            "httpService",
            "httpServiceUrlTemplate",
            "httpServiceMethod",
            "webService",
            "webServiceOperation",
            "webServiceParameter",
            "enumeration",
            "enumerationValue",
            "attribute",
            "dimension",
            "resource",
            "tabularSection",
            "form",
            "formAttribute",
            "formCommand",
            "formElement",
            "template",
            "spreadsheetDocumentTemplate",
            "command",
        ],
        SemanticObjectKind::as_str,
    );
    assert_complete_unique(
        SemanticEnumValue::ALL,
        &[
            "string",
            "number",
            "nonperiodical",
            "second",
            "day",
            "month",
            "quarter",
            "year",
            "recorderPosition",
            "allow",
            "deny",
            "hierarchyOfItems",
            "hierarchyOfGroupsAndItems",
            "balance",
            "turnovers",
            "independent",
            "recorderSubordinate",
            "dontCheck",
            "showError",
            "dontIndex",
            "index",
            "indexWithAdditionalOrder",
            "use",
            "dontUse",
            "forItem",
            "duringRequest",
            "duringSession",
            "in",
            "out",
            "inOut",
        ],
        SemanticEnumValue::as_str,
    );
}

#[test]
fn registries_parse_only_core_owned_stable_strings() {
    assert_eq!(
        SemanticPropertyId::parse("metadata.name"),
        Some(SemanticPropertyId::METADATA_NAME)
    );
    assert_eq!(
        SemanticRelationId::parse("attributes"),
        Some(SemanticRelationId::ATTRIBUTES)
    );
    assert_eq!(
        SemanticObjectKind::parse("document"),
        Some(SemanticObjectKind::Document)
    );
    assert_eq!(
        SemanticEnumValue::parse("recorderPosition"),
        Some(SemanticEnumValue::RECORDER_POSITION)
    );

    assert!(SemanticPropertyId::parse("adapter.custom").is_none());
    assert!(SemanticRelationId::parse("nativeChildren").is_none());
    assert!(SemanticObjectKind::parse("metadataObject:Native").is_none());
    assert!(SemanticEnumValue::parse("adapterValue").is_none());
}
